name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        browser: [chrome, firefox]  # Test only on Chrome and Firefox

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [[ ${{ matrix.browser }} == 'firefox' ]]; then
          brew install geckodriver  # Install GeckoDriver for Firefox
        elif [[ ${{ matrix.browser }} == 'chrome' ]]; then
          brew install --cask chromedriver  # Install ChromeDriver

    - name: Run tests
      run: |
        pytest tests/  # Run all tests in the /tests folder